#!/bin/bash
# Auto-generated by run_oj_beta_sweep.py
# Submits hollow-crown / slit beta-sweep jobs
set -e
cd /home/nishioka/IKM_Hiwi/Tmcmc202601/FEM

echo '=== OJ_Crown_T23_b030 ==='
abaqus job=OJ_Crown_T23_b030 inp=OJ_Crown_T23_b030.inp cpus=1 interactive

echo '=== OJ_Crown_T23_b070 ==='
abaqus job=OJ_Crown_T23_b070 inp=OJ_Crown_T23_b070.inp cpus=1 interactive

echo '=== OJ_Crown_T23_b100 ==='
abaqus job=OJ_Crown_T23_b100 inp=OJ_Crown_T23_b100.inp cpus=1 interactive

echo '=== OJ_Slit_T3031_b030 ==='
abaqus job=OJ_Slit_T3031_b030 inp=OJ_Slit_T3031_b030.inp cpus=1 interactive

echo '=== OJ_Slit_T3031_b070 ==='
abaqus job=OJ_Slit_T3031_b070 inp=OJ_Slit_T3031_b070.inp cpus=1 interactive

echo '=== OJ_Slit_T3031_b100 ==='
abaqus job=OJ_Slit_T3031_b100 inp=OJ_Slit_T3031_b100.inp cpus=1 interactive
