      SUBROUTINE USDFLD(FIELD,STATEV,PNEWDT,DIRECT,T,CELENT,
     1 TIME,DTIME,CMNAME,ORNAME,NFIELD,NSTATV,NOEL,NPT,LAYER,
     2 KSPT,KSTEP,KINC,NDI,NSHR,COORD,JMAC,JMATYP,MATLAYO,
     3 LACCFLA)

      INCLUDE 'ABA_PARAM.INC'

      CHARACTER*80 CMNAME, ORNAME
      DIMENSION FIELD(NFIELD), STATEV(NSTATV), DIRECT(3,3),
     1 T(3,3), TIME(2), COORD(*), JMAC(*), JMATYP(*)

      DOUBLE PRECISION E0, NU0, A_COEF, B_COEF, C_COEF
      DOUBLE PRECISION PHI_TOT, R_PG, E_LOC, NU_LOC

      E0     = 2.0D9
      NU0    = 0.30D0
      A_COEF = 0.50D0
      B_COEF = 0.80D0
      C_COEF = 0.05D0

      IF (NFIELD.GE.1) THEN
         PHI_TOT = FIELD(1)
      ELSE
         PHI_TOT = 0.0D0
      ENDIF
      IF (NFIELD.GE.2) THEN
         R_PG = FIELD(2)
      ELSE
         R_PG = 0.0D0
      ENDIF

      IF (PHI_TOT .LT. 0.0D0) PHI_TOT = 0.0D0
      IF (PHI_TOT .GT. 1.0D0) PHI_TOT = 1.0D0
      IF (R_PG .LT. 0.0D0) R_PG = 0.0D0
      IF (R_PG .GT. 1.0D0) R_PG = 1.0D0

      E_LOC  = E0 * (1.0D0 - A_COEF*PHI_TOT - B_COEF*R_PG)
      NU_LOC = NU0 + C_COEF*PHI_TOT

      IF (E_LOC .LT. 0.1D0*E0) E_LOC = 0.1D0*E0
      IF (NU_LOC .LT. 0.20D0) NU_LOC = 0.20D0
      IF (NU_LOC .GT. 0.49D0) NU_LOC = 0.49D0

      IF (NFIELD.GE.1) FIELD(1) = PHI_TOT
      IF (NFIELD.GE.2) FIELD(2) = R_PG

      IF (NSTATV.GE.1) STATEV(1) = E_LOC
      IF (NSTATV.GE.2) STATEV(2) = NU_LOC

      RETURN
      END
