"""Hold the implementation against a genuinely independent closed form.

`reference_values.json` is generated by calling the implementation, so
agreement with it establishes nothing. `closed_form_reference.py` derives the
same two cases from the continuum statement of the model and imports nothing
from the code under test, which makes this comparison real.

The comparison currently *fails* in the naive sense -- the implementation does
not reproduce the closed form for constrained growth. That is the known
mis-scaled isochoric split of DEVIATOR_SCALING_FINDING.md, and it is deliberate
that these tests do not paper over it with a loose tolerance. Instead they
assert the discrepancy equals the term that analysis predicts, in closed form,
to near machine precision. So the tests pin two things at once: that the
implementation has not drifted, and that our explanation of *why* it differs is
still correct. If someone fixes the split, `test_constrained_growth_...` fails
loudly and points at this file rather than silently passing.

Requires gfortran; skipped where absent.
"""
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import pytest

_ROOT = Path(__file__).resolve().parents[1]
_AU = _ROOT / "ansys_usermat"
_REF = _AU / "apdl" / "closed_form_reference.py"
_FC = shutil.which("gfortran")
_CC = shutil.which("cc") or shutil.which("gcc")

pytestmark = pytest.mark.skipif(
    _FC is None or _CC is None or not _REF.exists(),
    reason="gfortran/cc or the closed-form reference is unavailable")

sys.path.insert(0, str(_AU / "apdl"))
import closed_form_reference as cf  # noqa: E402

# The material of reference_values.json, so the two can be read side by side.
C10, C01, D1, MTYPE, DT = 2.0e-4, 0.0, 5000.0, 0.0, 5.0
I3 = np.eye(3)


@pytest.fixture(scope="module")
def core_exe():
    tmp = Path(tempfile.mkdtemp())
    o = {n: tmp / f"{n}.o" for n in ("hook", "core", "shim")}
    subprocess.run([_FC, "-c", "-ffixed-line-length-132", "-J", str(tmp),
                    str(_AU / "coupling" / "usermat_py_hook.f"),
                    "-o", str(o["hook"])], check=True, cwd=tmp)
    subprocess.run([_FC, "-c", "-ffixed-line-length-132", "-I", str(tmp),
                    str(_AU / "usermat_biofilm.f"), "-o", str(o["core"])],
                   check=True, cwd=tmp)
    subprocess.run([_CC, "-c", "-fPIC",
                    str(_AU / "coupling" / "biofilm_py_eval.c"),
                    "-o", str(o["shim"])], check=True)
    exe = tmp / "core"
    subprocess.run([_FC, "-ffixed-line-length-132", "-I", str(tmp),
                    str(_AU / "crosscheck" / "xcheck_driver_ans.f"),
                    str(o["core"]), str(o["hook"]), str(o["shim"]),
                    "-o", str(exe)], check=True)
    return exe


def _run(exe, F, Fv, alpha, eta):
    text = (" ".join(f"{F[i, j]:.17e}" for i in range(3) for j in range(3)) + "\n" +
            " ".join(f"{Fv[i, j]:.17e}" for i in range(3) for j in range(3)) + "\n" +
            f"{alpha:.17e} {C10:.17e} {C01:.17e} {D1:.17e} {eta:.17e} "
            f"{MTYPE:.1f} {DT:.17e}\n")
    r = subprocess.run([str(exe)], input=text, capture_output=True, text=True,
                       env={"PATH": "/usr/bin:/bin"}, timeout=30)
    assert r.returncode == 0, r.stderr
    v = [float(x) for x in r.stdout.split()]
    return np.array(v[:6]), np.array(v[6:15]).reshape(3, 3)


# --------------------------------------------------------------------------- #
def test_the_reference_is_actually_independent():
    """A closed form that imports the code it checks is not a closed form.

    Checked against the parsed module rather than its text, so that the
    docstring may name the implementation while explaining the circularity
    without tripping the guard.
    """
    import ast

    tree = ast.parse(_REF.read_text())
    imported = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            imported.update(a.name.split(".")[0] for a in node.names)
        elif isinstance(node, ast.ImportFrom) and node.module:
            imported.add(node.module.split(".")[0])

    assert imported <= {"numpy"}, (
        f"closed_form_reference.py imports {sorted(imported - {'numpy'})} — it "
        "must derive the answer, not obtain it from the implementation")

    # It must not shell out to the compiled code either.
    calls = {n.func.id for n in ast.walk(tree)
             if isinstance(n, ast.Call) and isinstance(n.func, ast.Name)}
    assert not (calls & {"eval", "exec", "compile", "__import__"}), calls


@pytest.mark.parametrize("alpha", [0.05, 0.20])
@pytest.mark.parametrize("eta", [0.0, 8.0e-3])
def test_free_growth_matches_the_closed_form(core_exe, alpha, eta):
    """Traction-free growth gives Fe = I exactly, so the stress vanishes for
    any material and any viscosity. This is also the one case where the coded
    and correct isochoric splits agree, since J_e = 1."""
    F = (1.0 + alpha) * I3
    sig, fv = _run(core_exe, F, I3, alpha, eta)
    np.testing.assert_allclose(sig, cf.free_growth_stress(), atol=1e-18)
    np.testing.assert_allclose(fv, I3, atol=1e-18)


@pytest.mark.parametrize("alpha", [0.05, 0.20])
def test_constrained_growth_differs_from_the_closed_form_by_exactly_the_predicted_term(
        core_exe, alpha):
    """The load-bearing test.

    The closed form says the deviator vanishes and only (2/D1)(J-1) survives.
    The implementation adds a spherical term, and DEVIATOR_SCALING_FINDING.md
    predicts that term in closed form. Assert the implementation equals
    closed form + prediction -- not merely that it is 'close'.
    """
    sig, _ = _run(core_exe, I3, I3, alpha, 0.0)
    exact = cf.constrained_stress(alpha, D1)
    predicted = exact + cf.spurious_term(alpha, C10)

    np.testing.assert_allclose(sig, predicted, rtol=1e-12, atol=1e-18)

    # And state the size of the gap, so a fix cannot pass unnoticed.
    assert not np.allclose(sig, exact, rtol=1e-6), (
        "the implementation now matches the closed form — the isochoric split "
        "appears to have been fixed. That is good news: update "
        "DEVIATOR_SCALING_FINDING.md, regenerate reference_values.json, and "
        "retire the spurious-term half of this test.")


@pytest.mark.parametrize("alpha", [0.05, 0.20])
def test_a_correct_deviator_would_make_eta_irrelevant_here(core_exe, alpha):
    """For an isotropic elastic state the deviatoric flow driver is zero, so a
    correct deviatoric dashpot cannot move Fv and the stress cannot depend on
    eta. The closed form has no eta in it at all. The implementation does
    depend on eta, and det(Fv) leaves 1 — a volumetric viscous flow out of a
    model documented as deviatoric."""
    s0, fv0 = _run(core_exe, I3, I3, alpha, 0.0)
    s1, fv1 = _run(core_exe, I3, I3, alpha, 8.0e-3)

    np.testing.assert_allclose(fv0, I3, atol=1e-18)          # eta=0 path
    assert np.max(np.abs(fv1 - I3)) > 1e-3, "no spurious flow to document"
    assert abs(np.linalg.det(fv1) - 1.0) > 1e-3, (
        "det(Fv) stayed 1 — the flow has become isochoric, i.e. the driver is "
        "now genuinely deviatoric; see the note in the previous test")
    assert abs(s1[0] - s0[0]) / abs(s0[0]) > 0.1, (
        "the eta dependence this test documents has gone")
