#!/usr/bin/env python3
"""Write refined copies of a deck by halving its ESIZE values.

For the study in MESH_STUDY.md. Deliberately dumb: it rewrites ESIZE and
nothing else, so a level differs from the original in exactly one respect and
a difference in the result cannot be blamed on anything the script did.

    python ansys_usermat/apdl/make_mesh_levels.py t_growth_cylinder_shell.dat
"""
import argparse
import re
import sys
from pathlib import Path


def refine(text, factor):
    """Halve every ESIZE, and drop the trailing comment on those lines.

    The originals carry comments like "0.3 thick -> 2 elements through", which
    stop being true the moment the size changes. A deck that describes itself
    wrongly is worse than one that says nothing, so the comment goes rather
    than silently misreporting the mesh.
    """
    def sub(m):
        return f"{m.group(1)}{float(m.group(2)) / factor:g}"
    return re.sub(r"(?im)^(\s*ESIZE\s*,\s*)([0-9.eEdD+-]+)[^\n]*", sub, text)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("deck", type=Path)
    ap.add_argument("--levels", type=int, default=2, help="how many refinements")
    a = ap.parse_args(argv)

    text = a.deck.read_text(errors="replace")
    if not re.search(r"(?im)^\s*ESIZE\s*,", text):
        raise SystemExit(f"{a.deck.name} has no ESIZE line to refine")

    for lvl in range(1, a.levels + 1):
        out = a.deck.with_name(f"{a.deck.stem}_mesh{lvl}{a.deck.suffix}")
        body = refine(text, 2 ** lvl)
        header = (f"! Mesh level {lvl}: ESIZE halved {lvl}x from "
                  f"{a.deck.name}. Generated by make_mesh_levels.py -- edit the\n"
                  f"! original, not this. See MESH_STUDY.md for what to do with it.\n")
        out.write_text(header + body)
        sizes = re.findall(r"(?im)^\s*ESIZE\s*,\s*([0-9.eEdD+-]+)", body)
        print(f"{out.name}: ESIZE -> {', '.join(sizes)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
