"""make_wired_deck.py -- derive a run deck from one of the partner's
Workbench decks (local, never committed) by changing only the user-material
constants, the time stepping and the post-processing.

    python ansys_usermat/apdl/make_wired_deck.py BASE.dat OUT.dat
        --props 7=1e-3,8=1,9=1,10=1,28=7,29=0.01,30=0.5
        [--elem 220] [--deltim 0.01] [--time 0.16] [--post all|elem|none]

--props  1-based prop(i)=value overrides on top of the base deck's material 1
         constants (missing ones are 0); the constant count becomes
         max(28, base count, highest i).
--elem   apply the constants to this element only (material 2, a copy of
         material 1); material 1 keeps the base deck's constants. Without
         --elem, material 1 itself is changed.
--post   all  : *USE,post_all_stress.mac  (all_stress.csv, last set)
         elem : *USE,post_elem_stress.mac,<elem>  (elem_stress.csv, every set)
         none : nothing (default: elem with --elem, else all)
         all/elem also put OUTRES,ALL,ALL right before SOLVE (the
         Workbench deck writes no element stresses otherwise).

An existing material-2 block (MPCOPY,,1,2 ... MPCHG,2,n) and existing
*USE,post_ lines in the base are replaced, so a derived deck can be a base.
Every edit must match exactly once, otherwise nothing is written. The output
is read back and its constants compared with what was asked for.
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

TB1 = re.compile(r"^TB,USER,1,1,(\d+),NONLINEAR\r?\n((?:TBDATA,.*\r?\n)+)", re.M | re.I)
MAT2 = re.compile(r"^MPCOPY,,1,2\r?\n(?:.*\r?\n)*?MPCHG,2,\d+[ \t]*\r?\n", re.M | re.I)
STATE1 = re.compile(r"^TB,STATE,1,,100[ \t]*\r?\n", re.M | re.I)
DELTIM = re.compile(r"^deltim,[^\r\n!]*", re.M | re.I)
TIME = re.compile(r"^time,[^\r\n!]*", re.M | re.I)
SOLVE = re.compile(r"^solve[ \t]*\r?$", re.M | re.I)
USEPOST = re.compile(r"^(?:FINISH\r?\n)?\*USE,post_[^\r\n]*\r?\n(?:FINISH\r?\n)?", re.M | re.I)


def stop(msg: str) -> None:
    sys.exit(f"STOP (nothing written): {msg}")


def parse_tbdata(block: str, n: int) -> list[float]:
    vals = [0.0] * n
    for line in block.splitlines():
        parts = [p.strip() for p in line.split(",")]
        start = int(parts[1])
        for k, p in enumerate(parts[2:]):
            if p:
                if start + k - 1 >= n:
                    vals.extend([0.0] * (start + k - n))
                vals[start + k - 1] = float(p)
    return vals


def tb_block(mat: int, vals: list[float], nl: str) -> str:
    out = [f"TB,USER,{mat},1,{len(vals)},NONLINEAR"]
    for i in range(0, len(vals), 6):
        out.append(f"TBDATA,{i + 1}," + ",".join(repr(float(v)) for v in vals[i:i + 6]))
    return nl.join(out) + nl


def only_one(rx, s, what):
    m = list(rx.finditer(s))
    if len(m) != 1:
        stop(f"{what}: {len(m)} matches, expected 1")
    return m[0]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("base")
    ap.add_argument("out")
    ap.add_argument("--props", default="")
    ap.add_argument("--elem", type=int)
    ap.add_argument("--deltim", type=float)
    ap.add_argument("--time", type=float)
    ap.add_argument("--post", choices=("all", "elem", "none"))
    a = ap.parse_args()

    raw = Path(a.base).read_bytes().decode("latin-1")
    nl = "\r\n" if "\r\n" in raw else "\n"
    s = re.sub(r"^! generated by make_wired_deck\.py[^\n]*\n", "", raw, flags=re.M)

    over = {}
    for item in filter(None, (x.strip() for x in a.props.split(","))):
        k, v = item.split("=")
        if int(k) < 1:
            stop(f"bad prop index {k}")
        over[int(k)] = float(v)

    m1 = only_one(TB1, s, "material 1 TB,USER block")
    base_vals = parse_tbdata(m1.group(2), int(m1.group(1)))
    n = max(28, len(base_vals), max(over, default=0))
    vals = base_vals + [0.0] * (n - len(base_vals))
    for k, v in over.items():
        vals[k - 1] = v

    s = MAT2.sub("", s)                              # drop an old material-2 block
    if a.elem is not None:
        st = only_one(STATE1, s, "TB,STATE,1,,100")
        blk = ("MPCOPY,,1,2" + nl + tb_block(2, vals, nl) + "TB,STATE,2,,100" + nl
               + f"MPCHG,2,{a.elem}" + nl)
        s = s[:st.end()] + blk + s[st.end():]
    else:
        s = s[:m1.start()] + tb_block(1, vals, nl) + s[m1.end():]

    if a.deltim is not None:
        only_one(DELTIM, s, "deltim")
        s = DELTIM.sub(f"deltim,{a.deltim!r},{a.deltim!r},{a.deltim!r}", s)
    if a.time is not None:
        only_one(TIME, s, "time")
        s = TIME.sub(f"time,{a.time!r}", s)

    post = a.post or ("elem" if a.elem is not None else "all")
    s = USEPOST.sub("", s)
    if post != "none":
        # the macros read element stresses: the Workbench deck writes none
        # (outres,all,none) unless OUTRES,ALL,ALL comes before SOLVE
        sv = only_one(SOLVE, s, "solve")
        if not re.search(r"^OUTRES,ALL,ALL[ \t]*\r?\n\Z", s[:sv.start()], re.M | re.I):
            s = s[:sv.start()] + "OUTRES,ALL,ALL" + nl + s[sv.start():]
    if not s.endswith(nl):
        s += nl
    if post == "all":
        s += f"FINISH{nl}*USE,post_all_stress.mac{nl}FINISH{nl}"
    elif post == "elem":
        if a.elem is None:
            stop("--post elem needs --elem")
        s += f"FINISH{nl}*USE,post_elem_stress.mac,{a.elem}{nl}FINISH{nl}"

    head = (f"! generated by make_wired_deck.py from {Path(a.base).name}: props {a.props or '-'}"
            f", elem {a.elem}, deltim {a.deltim}, time {a.time}, post {post}{nl}")
    s = head + s

    # read back: the constants in the written deck are what was asked for
    if a.elem is not None:
        m2 = re.search(r"^TB,USER,2,1,(\d+),NONLINEAR\r?\n((?:TBDATA,.*\r?\n)+)", s, re.M)
        got = parse_tbdata(m2.group(2), int(m2.group(1)))
        keep = parse_tbdata(only_one(TB1, s, "material 1 after edit").group(2), int(m1.group(1)))
        if keep != base_vals:
            stop("material 1 changed although --elem was given")
    else:
        m = only_one(TB1, s, "material 1 after edit")
        got = parse_tbdata(m.group(2), int(m.group(1)))
    if got != vals:
        stop(f"read-back mismatch: {got} vs {vals}")

    Path(a.out).write_bytes(s.encode("latin-1"))
    nz = {i + 1: v for i, v in enumerate(vals) if v != 0.0}
    print(f"OK: {a.out}  ({n} constants{', material 2 on elem ' + str(a.elem) if a.elem is not None else ''})")
    print(f"  nonzero props: {nz}")


if __name__ == "__main__":
    main()
