#!/usr/bin/env python3
"""Generate closed-form reference stresses for the ANSYS growth benchmark.

The uniaxial `SOLID185` benchmark that validated the USERMAT interface on
ANSYS 2022 R2 exercised the *mechanical* path. It did not exercise growth,
because `alpha = 0` leaves `Fg = I` and the growth branch is never entered.

This generates the reference for a growth-specific check that needs **no FE
solve to predict**: a single element with every node fully fixed. Then

    F = I  exactly,     Fg = (1+alpha) I,     Fe = Fg^-1  (elastic case)

so the Cauchy stress follows directly from the constitutive core. Any
disagreement between ANSYS and these numbers is a growth-path bug, isolated
from meshing, boundary conditions and the global Newton solve.

The expected answer is pure hydrostatic compression: constrained isotropic
growth can only put the element into uniform pressure, with all shear
components identically zero. That shear-free structure is itself a check --
a nonzero shear term would mean the Voigt map (VI/VJ) is mis-wired.

Usage:
    python3 make_reference.py            # rewrite reference_values.json
    python3 make_reference.py --check    # verify the committed file matches
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import numpy as np

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent / "coupling"))

from material_server import stress_core  # noqa: E402

REFERENCE = _HERE / "reference_values.json"

# Biofilm-scale properties, matching the crosscheck battery's base case.
C10, C01, D1, MTYPE = 0.2e-3, 0.0, 1.0 / (0.2e-3), 0
DT = 5.0

CASES = [
    # (label, alpha, eta)
    ("elastic_a005", 0.05, 0.0),
    ("viscous_a005", 0.05, 8e-3),
    ("elastic_a020", 0.20, 0.0),
    ("viscous_a020", 0.20, 8e-3),
]


def build() -> dict:
    I3 = np.eye(3)
    cases = {}
    for label, alpha, eta in CASES:
        # fully constrained single element => F = I
        sv, _fv, je = stress_core(I3, I3, alpha, C10, C01, D1, eta, MTYPE, DT)
        cases[label] = {
            "alpha": alpha,
            "eta": eta,
            "Je": je,
            # ANSYS Voigt order: 11, 22, 33, 12, 23, 13
            "stress": [float(x) for x in sv],
            "hydrostatic": float(sv[0]),
        }
    return {
        "description": (
            "REGRESSION SNAPSHOT, not a closed form. Cauchy stress for a fully "
            "constrained single element (F = I) under isotropic growth "
            "Fg = (1+alpha)I, obtained by CALLING stress_core -- so these "
            "values record what the implementation does and cannot test "
            "whether it is right. They are useful only for detecting drift. "
            "For an independent check see apdl/closed_form_reference.py and "
            "tests/test_closed_form_reference.py, which derive the same cases "
            "from the continuum model; the constrained case differs from these "
            "values by the spherical term described in "
            "DEVIATOR_SCALING_FINDING.md. ANSYS Voigt order 11,22,33,12,23,13. "
            "Generated by make_reference.py; do not hand-edit."
        ),
        "properties": {"C10": C10, "C01": C01, "D1": D1, "mtype": MTYPE, "dt": DT},
        "cases": cases,
    }


def main(argv=None) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare against the committed file instead of rewriting it")
    args = ap.parse_args(argv)

    payload = build()

    if args.check:
        if not REFERENCE.exists():
            print(f"{REFERENCE} missing", file=sys.stderr)
            return 1
        committed = json.loads(REFERENCE.read_text())
        if committed != payload:
            print("reference_values.json is stale — re-run make_reference.py", file=sys.stderr)
            return 1
        print("reference_values.json matches the constitutive core")
        return 0

    REFERENCE.write_text(json.dumps(payload, indent=2) + "\n")
    print(f"wrote {REFERENCE}")
    for label, c in payload["cases"].items():
        print(f"  {label:14s} alpha={c['alpha']:<5} eta={c['eta']:<7} "
              f"Je={c['Je']:.9f}  sigma_hyd={c['hydrostatic']:.9e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
