#!/usr/bin/env python3
"""Assemble the self-contained package handed to the partner group.

The point of generating it rather than keeping a copy is that a hand-maintained
second copy of a verified routine drifts. Everything here is extracted from the
sources under test, so the package cannot silently fall behind them.

What gets extracted, and why it is possible: `usermat` in usermat_biofilm.f
`use`s the Python-coupling bridge, but BIOFILM_STRESS_CORE and its matrix
helpers do not -- the `use` sits inside `usermat` only. So the constitutive
core lifts out with no dependency on the coupling layer, the C shim, or
anything else in this repository.

Usage:  python handover/make_handover.py [-o OUTDIR]
Then:   verified by tests/test_handover_package.py
"""
import argparse
import re
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC_CORE = ROOT / "ansys_usermat" / "usermat_biofilm.f"
SRC_WRAP = ROOT / "ansys_usermat" / "biofilm_material_v01.f"
SRC_DRV = ROOT / "ansys_usermat" / "crosscheck" / "wrapper_driver.f"

# Everything from BIOFILM_STRESS_CORE to the end of the file: the core plus
# INIT_FV_IF_ZERO and the MAT_* helpers it calls. Nothing above it is needed.
_START = re.compile(r"^      subroutine BIOFILM_STRESS_CORE\b", re.M)

HEADER = """C=======================================================================
C  biofilm_stress_core.f
C
C  The verified constitutive core, extracted verbatim from
C  usermat_biofilm.f in the pde-fem-biofilm repository. It is the routine
C  BIOFILM_GROWTH_VISCO_V01 calls; the two files together are the whole
C  package and depend on nothing else.
C
C  Verified 0 ULP against an independently written Abaqus UMAT over 8017
C  deformation states, found by adversarial search rather than sampling.
C
C  Extracted, not rewritten: this file is generated by
C  handover/make_handover.py so it cannot drift from the tested source.
C  Please do not edit it here -- changes should go back to the repository
C  so the verification still applies.
C=======================================================================
"""


def extract_core(text: str) -> str:
    m = _START.search(text)
    if m is None:
        raise SystemExit("BIOFILM_STRESS_CORE not found -- has usermat_biofilm.f moved?")
    return HEADER + text[m.start():].rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", "--outdir", type=Path,
                    default=ROOT / "handover" / "out")
    args = ap.parse_args()
    out = args.outdir
    if out.exists():
        shutil.rmtree(out)
    out.mkdir(parents=True)

    (out / "biofilm_stress_core.f").write_text(
        extract_core(SRC_CORE.read_text()))
    shutil.copy2(SRC_WRAP, out / "biofilm_material_v01.f")
    shutil.copy2(SRC_DRV, out / "wrapper_driver.f")
    shutil.copy2(Path(__file__).parent / "README.md", out / "README.md")
    fig = ROOT / "assets" / "flow_oliver_solution_loop.png"
    if fig.exists():
        shutil.copy2(fig, out / "solution_loop.png")

    print(f"package written to {out}")
    for p in sorted(out.iterdir()):
        print(f"  {p.name:28s} {p.stat().st_size:>8,d} bytes")


if __name__ == "__main__":
    main()
