#!/usr/bin/env python3
"""Remove AI-attribution footers from this repository's pull request bodies.

CLAUDE.md forbids marking any surface a reader sees as AI-assisted -- commit
messages and pull requests alike -- and records that existing PR bodies were
cleaned on 2026-09-01. They were not: 19 of them still carry a footer, among
them #31, whose own subject is forbidding exactly this. The footers are
appended by tooling after the body is written, so this recurs on every new PR
and a one-off cleanup is not enough; this script is the thing to re-run.

Why a script rather than editing them by hand. There is no `gh` CLI and no
direct API access from the assistant's environment, so a manual fix means
retyping each body in full, and a transcription slip silently damages a
historical record. Here the body is fetched, the footer is removed by an exact
string match, and everything else is written back byte-identical -- or the PR
is skipped.

    python scripts/strip_pr_ai_footer.py                # dry run, prints diffs
    python scripts/strip_pr_ai_footer.py --apply
    python scripts/strip_pr_ai_footer.py --apply --pr 31 --pr 45

The token is read from `.env` (GITHUB_PAT=...) and never printed. Nothing else
about a body is touched: CodeRabbit summaries and the like are review-tool
output, not a claim about who wrote the work, and are left alone.
"""
import argparse
import json
import os
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

REPO = "keisuke58/pde-fem-biofilm"
API = "https://api.github.com"

# Each pattern matches one whole footer block including the blank lines and any
# horizontal rule that introduces it, so removing it leaves no orphaned "---".
FOOTERS = [
    re.compile(r"\n*(?:\r?\n)-{3,}\r?\n_Generated by \[Claude Code\]\([^)]*\)_\s*", re.I),
    re.compile(r"\n*🤖 Generated with \[Claude Code\]\([^)]*\)\s*", re.I),
    re.compile(r"\n*Generated with \[Claude Code\]\([^)]*\)\s*", re.I),
    re.compile(r"\n*https://claude\.ai/code/session_[A-Za-z0-9]+\s*", re.I),
    re.compile(r"\n*Claude-Session:\s*\S+\s*", re.I),
    re.compile(r"\n*Co-Authored-By:\s*Claude[^\n]*\n?", re.I),
]


def token():
    env = Path(__file__).resolve().parents[1] / ".env"
    if not env.exists():
        sys.exit(f"{env} not found; it must contain GITHUB_PAT=<token>")
    for line in env.read_text(encoding="utf-8", errors="replace").splitlines():
        k, _, v = line.partition("=")
        if k.strip() in ("GITHUB_PAT", "GH_TOKEN", "GITHUB_TOKEN"):
            return v.strip().strip('"').strip("'")
    sys.exit("no GITHUB_PAT in .env")


def call(path, tok, method="GET", payload=None):
    req = urllib.request.Request(
        f"{API}{path}", method=method,
        data=json.dumps(payload).encode() if payload else None,
        headers={"Authorization": f"Bearer {tok}",
                 "Accept": "application/vnd.github+json",
                 "Content-Type": "application/json",
                 "User-Agent": "strip-pr-ai-footer"})
    try:
        with urllib.request.urlopen(req) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        # Never let a token reach the console, even inside an error body.
        msg = e.read().decode(errors="replace").replace(tok, "<redacted>")
        sys.exit(f"{method} {path} -> {e.code}: {msg[:400]}")


def clean(body):
    """Remove every footer block, leaving the rest of the body as it was.

    Substituting a blank line rather than nothing matters: a footer sitting
    between two sections would otherwise weld them together, and a heading that
    loses its preceding blank line is a formatting change this script has no
    business making. Runs of blank lines are then collapsed back to one.
    """
    out = body or ""
    for pat in FOOTERS:
        out = pat.sub("\n\n", out)
    out = re.sub(r"\n{3,}", "\n\n", out)
    return out.rstrip() + "\n" if out.strip() else out


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true",
                    help="write the cleaned bodies back (default: dry run)")
    ap.add_argument("--pr", type=int, action="append", default=None,
                    help="only this PR number; repeatable")
    a = ap.parse_args(argv)

    tok = token()
    if a.pr:
        prs = [call(f"/repos/{REPO}/pulls/{n}", tok) for n in a.pr]
    else:
        prs, page = [], 1
        while True:
            batch = call(f"/repos/{REPO}/pulls?state=all&per_page=100&page={page}", tok)
            if not batch:
                break
            prs += batch
            page += 1

    dirty = 0
    for pr in prs:
        body = pr.get("body") or ""
        new = clean(body)
        if new == body:
            continue
        dirty += 1
        removed = len(body) - len(new)
        print(f"#{pr['number']:<4} {pr['title'][:64]:<64} -{removed} chars")
        if a.apply:
            call(f"/repos/{REPO}/pulls/{pr['number']}", tok, "PATCH", {"body": new})
            print(f"       cleaned")

    print(f"\n{dirty} of {len(prs)} pull requests carry an AI-attribution footer.")
    if dirty and not a.apply:
        print("Dry run. Re-run with --apply to remove them.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
