"""compare_wp2.py -- the twelve Abaqus WP2 runs (homeostatic-pressure growth
law, RUN_WP2_IKMHIWI03.md) against the axisymmetric prototype
keio_wp2/results_nutrient_bc.json (homeostatic_nutrient.py --bc).

    python abaqus_composition/compare_wp2.py [--out abaqus_composition/results_1007/compare_wp2.md]

Per run: largest compressive hoop stress -sigma_tt on the inner face (titanium
or enamel) and its height z, largest von Mises, mean alpha - 1. Abaqus values
come from summarize_implant.py (theta means per ring, Pa): the hoop stress
from the inner ring, von Mises from both rings, alpha - 1 as the mean of the
two rings (the prototype's is the volume mean, so this is approximate).
Missing runs are listed as such.
"""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent


def rings(path: Path):
    """{'inner': rows, 'outer': rows}, rows = dicts of the printed columns."""
    out, cur, head = {}, None, None
    for line in path.read_text().splitlines():
        s = line.strip()
        if s.startswith("inner"):
            cur = out.setdefault("inner", [])
        elif s.startswith("outer"):
            cur = out.setdefault("outer", [])
        elif s.startswith("z mm"):
            head = s.replace("z mm", "z").split()
        elif cur is not None and head and s and s[0].isdigit():
            v = [float(x) for x in s.split()]
            if len(v) == len(head):
                cur.append(dict(zip(head, v)))
    return out


def abaqus(path: Path):
    r = rings(path)
    inner, outer = r.get("inner", []), r.get("outer", [])
    if not inner:
        return None
    k = max(inner, key=lambda x: -x["s_tt"])
    both = inner + outer
    return dict(hoop=-k["s_tt"], z=k["z"], vm=max(x["vM"] for x in both),
                alpha=sum(x["alpha-1"] for x in both) / len(both))


def proto(run):
    f, h = run["field"], run["hist"][-1]
    stt = [-x for x in f["stt"]]
    i = max(range(len(stt)), key=stt.__getitem__)
    return dict(hoop=stt[i], z=f["z"][i], vm=h[4], alpha=h[1])


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(HERE / "results_1007" / "compare_wp2.md"))
    a = ap.parse_args()
    P = json.loads((ROOT / "keio_wp2" / "results_nutrient_bc.json").read_text())["runs"]
    rows = ["| shape | bottom | feedback | hoop max [Pa] Abaqus / prototype | at z [mm] | von Mises max [Pa] | alpha - 1 mean |",
            "|---|---|---|---|---|---|---|"]
    for geo, bulge in (("imp", 0.0), ("tooth", 1.0)):
        for base, pb in (("free", "free"), ("uz", "uz"), ("clamped", "clamped")):
            for tag, ph in (("none", None), ("ph01", 0.1)):
                pr = next(proto(r) for r in P if r["bulge"] == bulge and r["bottom"] == pb and r["P_h"] == ph)
                f = HERE / "results_1007" / f"wp2_{geo}_{base}_{tag}.txt"
                ab = abaqus(f) if f.exists() else None
                name = "implant" if geo == "imp" else "tooth"
                fb = "none" if ph is None else "P_h = 0.1"
                if ab is None:
                    rows.append(f"| {name} | {base} | {fb} | (missing) / {pr['hoop']:.2e} | - / {pr['z']:.2f} | - / {pr['vm']:.2e} | - / {pr['alpha']:.2e} |")
                    continue
                rows.append(f"| {name} | {base} | {fb} | {ab['hoop']:.2e} / {pr['hoop']:.2e} | {ab['z']:.2f} / {pr['z']:.2f}"
                            f" | {ab['vm']:.2e} / {pr['vm']:.2e} | {ab['alpha']:.2e} / {pr['alpha']:.2e} |")
    txt = ("# WP2: Abaqus (3D sector) against the axisymmetric prototype\n\n"
           "Generated by compare_wp2.py. Each cell: Abaqus / prototype. Abaqus: 6x24x20 C3D8T, dt 0.002;"
           " prototype: 8x64 axisymmetric, dt 0.01. Both T* = 1, consumption g phi c, front term w = 0.5,"
           " P_h with the local-stiffness form.\n\n" + "\n".join(rows) + "\n")
    Path(a.out).write_text(txt)
    print(txt)


if __name__ == "__main__":
    main()
