"""make_umat.py -- one Abaqus user-subroutine file with the same composition
coupling the ANSYS runs use (Keio continuation: the model moves to Abaqus).

    python abaqus_composition/make_umat.py OUT.for

The ANSYS side pastes the call-site fragments (ansys_usermat/apdl/callsite/)
into the partner's usermat. Here the same fragments, unchanged, go into a
small UMAT, so the point model, the composition (prop(28) = 7) and Eq. 36
run the same code in both programs. The file holds, in this order:
  - usermat_py_hook.f (module biofilm_py_bridge, the Fortran side of the
    Python bridge), split_rates.f (module biofilm_split, the per-point cache),
    growth_from_phi.f (Eq. 36), biofilm_material_v01.f (stress from
    F_g = (1+alpha) I with the Klempt 2024 stiffness branch) and, from
    usermat_biofilm.f, BIOFILM_STRESS_CORE and its helpers (the ANSYS
    entry point is left out);
  - UMAT, which checks the sizes and calls BIOFILM_COMP_UMAT;
  - BIOFILM_COMP_UMAT, which sets the names the fragments expect from the
    partner's usermat, includes the two fragments and turns alpha into stress.

Inputs from the Abaqus model:
  field variable 1 = phi, the amount of biofilm (Klempt 2024 phi; the ANSYS
                     runs take it from the partner's field), value at the end
                     of the increment
  field variable 2 = nutrient c (used with prop(33) = c_ref > 0)
  constants 1-42   = the ANSYS prop layout (prop(7) k_alpha, prop(8:27) theta,
                     prop(28) mode, prop(29:42) as in phi_mode_exec.inc:
                     37 number of species, 38-42 growth weights)
  constants 43-46  = E, E_void, nu, nu_void as biofilm_material_v01.f reads
                     them (E_void < 0 selects the Klempt 2024 stiffness)
  *DEPVAR >= 100   = the ANSYS state layout (72-83 point model, 84 alpha - 1),
                     85-93 the viscous state F_v
The C shim (ansys_usermat/coupling/biofilm_py_eval.c) is compiled separately
and linked through the job's abaqus_v6.env (run_comp.ps1 does both).
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AU = ROOT / "ansys_usermat"
CS = AU / "apdl" / "callsite"
sys.path.insert(0, str(AU / "apdl"))
import paste_fragments as pf  # noqa: E402

PARTS = [AU / "coupling" / "usermat_py_hook.f", CS / "split_rates.f",
         AU / "growth_from_phi.f", AU / "biofilm_material_v01.f",
         AU / "usermat_biofilm.f"]
# usermat_biofilm.f: only from BIOFILM_STRESS_CORE on (the stress core and its
# matrix helpers); its ANSYS entry point usermat would need ANSYS symbols
FROM = {"usermat_biofilm.f": "subroutine BIOFILM_STRESS_CORE"}


def part_lines(p: Path) -> list[str]:
    lines = p.read_text(encoding="latin-1").splitlines()
    key = FROM.get(p.name)
    if key:
        lines = lines[next(i for i, l in enumerate(lines) if l.strip().startswith(key)):]
    return lines

UMAT = """\
C=======================================================================
C  UMAT: Abaqus entry point (generated by abaqus_composition/make_umat.py)
C=======================================================================
      SUBROUTINE UMAT(STRESS, STATEV, DDSDDE, SSE, SPD, SCD,
     1 RPL, DDSDDT, DRPLDE, DRPLDT,
     2 STRAN, DSTRAN, TIME, DTIME, TEMP, DTEMP, PREDEF, DPRED,
     3 CMNAME, NDI, NSHR, NTENS, NSTATV, PROPS, NPROPS, COORDS,
     4 DROT, PNEWDT, CELENT, DFGRD0, DFGRD1, NOEL, NPT, LAYER,
     5 KSPT, JSTEP, KINC)
      INCLUDE 'ABA_PARAM.INC'
      CHARACTER*80 CMNAME
      DIMENSION STRESS(NTENS), STATEV(NSTATV), DDSDDE(NTENS,NTENS),
     1 DDSDDT(NTENS), DRPLDE(NTENS), STRAN(NTENS), DSTRAN(NTENS),
     2 TIME(2), PREDEF(1), DPRED(1), PROPS(NPROPS), COORDS(3),
     3 DROT(3,3), DFGRD0(3,3), DFGRD1(3,3), JSTEP(4)
      IF (NTENS .NE. 6 .OR. NSTATV .LT. 100 .OR. NPROPS .LT. 46) THEN
        WRITE(7,*) 'BIOFILM UMAT needs NTENS = 6, *DEPVAR >= 100',
     1             ' and 46 constants'
        CALL XIT
      END IF
      CALL BIOFILM_COMP_UMAT(STRESS, STATEV, DDSDDE, SSE, DTIME,
     1  PREDEF, DPRED, NSTATV, PROPS, NPROPS, PNEWDT, DFGRD1,
     2  NOEL, NPT, JSTEP(1), KINC)
      RETURN
      END

C=======================================================================
C  BIOFILM_COMP_UMAT: the ANSYS call-site fragments in an Abaqus UMAT
C=======================================================================
      SUBROUTINE BIOFILM_COMP_UMAT(STRESS, ustatev, DDSDDE, SSE,
     1  dTime, PREDEF, DPRED, NSTATV, prop, nProp, PNEWDT, DFGRD1,
     2  elemId, kDomIntPt, ldstep, isubst)
      USE biofilm_py_bridge
      USE biofilm_split
      IMPLICIT NONE
      INTEGER NSTATV, nProp, elemId, kDomIntPt, ldstep, isubst
      DOUBLE PRECISION STRESS(6), ustatev(NSTATV), DDSDDE(6,6), SSE
      DOUBLE PRECISION dTime, PREDEF(*), DPRED(*), prop(nProp)
      DOUBLE PRECISION PNEWDT, DFGRD1(3,3)
C     names the fragments expect from the partner's usermat
      DOUBLE PRECISION Sdp_bio1_n, Sdp_locbio1_n, Sdp_bio2_n
      DOUBLE PRECISION Sdp_locbio2_n, Sdp_sumLocal, Sbio_GrowthConst
      INTEGER keycut
C     Abaqus side: nutrient, mechanics, Voigt map (ANSYS 23/13 -> 13/23)
      DOUBLE PRECISION AB_C, AB_SIG(6), AB_TAN(6,6), AB_W
      DOUBLE PRECISION AB_FV(3,3), AB_FV1(3,3)
      INTEGER AB_KC, AB_I, AB_J, AB_MAP(6)
      DATA AB_MAP /1, 2, 3, 4, 6, 5/
C     trace files: Abaqus runs in a scratch directory that is removed at
C     the end and keeps units below 100 for itself, so the fragments'
C     units 95-99 are moved to 195-199 (make_umat.py) and opened here, once,
C     in the job's output directory
      LOGICAL AB_OPENED
      SAVE AB_OPENED
      DATA AB_OPENED /.FALSE./
      CHARACTER*256 AB_DIR
      INTEGER AB_LD
{decl}
C     --- host values: phi and c from field variables 1 and 2 ----------
      Sdp_bio1_n = PREDEF(1) + DPRED(1)
      Sdp_bio2_n = 0.0D0
      Sdp_locbio1_n = 1.0D0
      Sdp_locbio2_n = 1.0D0
      Sdp_sumLocal = 1.0D0
      AB_C = PREDEF(2) + DPRED(2)
      Sbio_GrowthConst = ustatev(84)
      keycut = 0
      IF (.NOT. AB_OPENED) THEN
        CALL GETOUTDIR(AB_DIR, AB_LD)
        OPEN(195, FILE=AB_DIR(1:AB_LD)//'/age_trace.csv',
     1       STATUS='UNKNOWN', POSITION='APPEND')
        OPEN(196, FILE=AB_DIR(1:AB_LD)//'/comp_trace.csv',
     1       STATUS='UNKNOWN', POSITION='APPEND')
        OPEN(197, FILE=AB_DIR(1:AB_LD)//'/phi_trace.csv',
     1       STATUS='UNKNOWN', POSITION='APPEND')
        OPEN(198, FILE=AB_DIR(1:AB_LD)//'/pm_trace.csv',
     1       STATUS='UNKNOWN', POSITION='APPEND')
        OPEN(199, FILE=AB_DIR(1:AB_LD)//'/split_trace.csv',
     1       STATUS='UNKNOWN', POSITION='APPEND')
        AG_TRACE_OPEN = .TRUE.
        CM_TRACE_OPEN = .TRUE.
        TRACE_OPEN = .TRUE.
        PM_TRACE_OPEN = .TRUE.
        SP_TRACE_OPEN = .TRUE.
        AB_OPENED = .TRUE.
      END IF
{exec}
C     --- stress from F_g = (1 + alpha) I, as in the ANSYS runs --------
      DO AB_J = 1, 3
        DO AB_I = 1, 3
          AB_FV(AB_I, AB_J) = ustatev(84 + AB_I + 3 * (AB_J - 1))
        END DO
      END DO
      IF (AB_FV(1,1) .EQ. 0.0D0) THEN
        DO AB_J = 1, 3
          DO AB_I = 1, 3
            AB_FV(AB_I, AB_J) = 0.0D0
          END DO
          AB_FV(AB_J, AB_J) = 1.0D0
        END DO
      END IF
      AB_KC = 0
      CALL BIOFILM_GROWTH_VISCO_V01(DFGRD1, AB_SIG, AB_TAN,
     1  prop(43), prop(44), prop(45), prop(46),
     2  Sdp_bio1_n + Sdp_bio2_n, Sbio_GrowthConst, AB_FV, AB_FV1,
     3  0.0D0, dTime, 0.0D0, 0.0D0, AB_W, AB_KC, elemId)
      DO AB_I = 1, 6
        STRESS(AB_I) = AB_SIG(AB_MAP(AB_I))
        DO AB_J = 1, 6
          DDSDDE(AB_I, AB_J) = AB_TAN(AB_MAP(AB_I), AB_MAP(AB_J))
        END DO
      END DO
      DO AB_J = 1, 3
        DO AB_I = 1, 3
          ustatev(84 + AB_I + 3 * (AB_J - 1)) = AB_FV1(AB_I, AB_J)
        END DO
      END DO
      SSE = AB_W
      IF (keycut .NE. 0 .OR. AB_KC .NE. 0) PNEWDT = 0.5D0
      RETURN
      END
"""


def build() -> str:
    decl = pf.read_lines(CS / "phi_mode_decl.inc")
    exe = pf.set_nut_source(pf.read_lines(CS / "phi_mode_exec.inc"), "AB_C")
    # units 95-99 -> 195-199 (Abaqus keeps units below 100); opened by the wrapper
    exe = [re.sub(r"\b(OPEN|WRITE|FLUSH)\((9[5-9])\b", r"\g<1>(1\2", l) for l in exe]
    assert not any(re.search(r"\b(OPEN|WRITE|FLUSH)\(9[5-9]\b", l) for l in exe)
    out = [f"C  generated by abaqus_composition/make_umat.py from {', '.join(p.name for p in PARTS)},",
           "C  phi_mode_decl.inc, phi_mode_exec.inc -- do not edit, regenerate"]
    for p in PARTS:
        out += [f"C ---- {p.relative_to(ROOT).as_posix()} ----"] + part_lines(p)
    out += UMAT.format(decl="\n".join(decl), exec="\n".join(exe)).splitlines()
    return "\n".join(out) + "\n"


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    Path(sys.argv[1]).write_text(build(), encoding="latin-1")
    print(f"wrote {sys.argv[1]}")
